### ISSUE TITLE
Configure database for Heroku deployment

### ISSUE THREAD

**Issue by jarifibrahim** [OpenSourceHelpCommunity/OpenSourceHelpCommunity.github.io#46]
The following error occurs when user tries to login/signup on
```
OperationalError at /accounts/login/
no such table: auth_user
```

**Comment by tapaswenipathak** [comment]
@jarifibrahim This issue is still present as the build has failed. Can you please look into it, reopening this.

**Comment by jarifibrahim** [comment]
@tapasweni-pathak The build failed as we do not have `psycopg2` in `requirements.txt`. We do not need `psycopg2` to run the app locally but Heroku uses `PostgreSQL` database instead of `SQLite`, so it needs `psycopg2`. This issue has been resolved. 
I'll open a new issue and PR for the Heroku build failure.

**Comment by tapaswenipathak** [comment]
This was quick! :)

**Comment by tapaswenipathak** [comment]
@jarifibrahim Checks logs the issue still persist
```
2017-07-06T05:46:08.746218+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/query.py", line 517, in has_results
2017-07-06T05:46:08.746218+00:00 app[web.1]:     return compiler.has_results()
2017-07-06T05:46:08.746219+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 845, in has_results
2017-07-06T05:46:08.746219+00:00 app[web.1]:     return bool(self.execute_sql(SINGLE))
2017-07-06T05:46:08.746219+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 886, in execute_sql
2017-07-06T05:46:08.746220+00:00 app[web.1]:     raise original_exception
2017-07-06T05:46:08.746220+00:00 app[web.1]: ProgrammingError: relation "auth_user" does not exist
2017-07-06T05:46:08.746221+00:00 app[web.1]: LINE 1: SELECT (1) AS "a" FROM "auth_user" WHERE "auth_user"."userna...
2017-07-06T05:46:08.746221+00:00 app[web.1]:                                ^
2017-07-06T05:46:08.746222+00:00 app[web.1]: 
2017-07-06T05:46:08.878511+00:00 heroku[router]: at=info method=POST path="/accounts/register/" host=opensourcehelpcommunity-dev.herokuapp.com request_id=5374cb7b-f2dd-43b6-98a2-1dda71450447 fwd="203.13.146.53" dyno=web.1 connect=0ms service=163ms status=500 bytes=143410 protocol=http
```

We are on Python 3, I will push a runtime.txt, so Heroku stops using Python 2.7 here.


Edit1:

As manage.py is not present in heroku local, I am not able to run 
```
heroku run python manage.py migrate
```
from heroku console.

Edit2:
Fixed, with Heroku bash it worked.
